apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: g6hcpam6k-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a0a930473f.6l52.p3.openshiftapps.com/rhtap/rhtap-qe:9e7f19e1730e7389c9302e4c88a096b8f37da029@sha256:481690c6e735ebbf6831c4ae3c746d7392095c9fbfc47d4f689ec8d5528b5d99
          name: container-image
